# Generated by Selenium IDE
from time import sleep

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys


class TestTmp():
    def setup_method(self, method):
        chrome_arg = webdriver.ChromeOptions()
        chrome_arg.debugger_address = '127.0.0.1:9222'
        self.driver = webdriver.Chrome(options=chrome_arg)
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_main_tmp(self):
        #基于首页登录

        self.driver.get("https://work.weixin.qq.com/")
        self.driver.find_element(By.XPATH,"//*[@class='index_top_operation_loginBtn']").click()
        self.driver.find_element(By.XPATH,"//*[@class='login_registerBar_link']").click()
        self.driver.find_element(By.XPATH,"//*[@id='corp_name']").send_keys("小蘑菇")
        sleep(2)
        self.driver.close()

    def test_login_tmp(self):

        #基于浏览器复用后的内容进行操作

        self.driver.get("https://work.weixin.qq.com/wework_admin/frame")
        self.driver.find_element(By.XPATH, "//*[@id ='menu_contacts']").click()

    def test_cookie_login(self):
        #利用cookie进行登录

        #存入cookie

       #cookies = self.driver.get_cookies()
        with open("tmp2.text","w",encoding="utf-8")as f:
            (json.dump(cookies))
      # print(cookies)
       # 读取cookie

     self.driver.get("https://work.weixin.qq.com/wework_admin/frame#index")
     with open("tmp.text","r",encoding="utf-8") as f:
         raw cookies = f.read()
         # 序列化
         cookies = json.loads(raw_cookies)
     for i in cookies:
          self.driver.add_cookie(i)
      self.driver.refresh()
      sleep(6)


